"""Add vote counts to Review model.

Revision ID: 5842dab8d19b
Revises: cbc821e170fa
Create Date: 2020-06-13 12:00:01.270825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5842dab8d19b'
down_revision = 'cbc821e170fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('downVoteCount', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('upVoteCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'upVoteCount')
    op.drop_column('reviews', 'downVoteCount')
    # ### end Alembic commands ###
