"""updating tables

Revision ID: 9d78cbdc5dc6
Revises: c426972d529a
Create Date: 2020-06-08 09:33:19.454062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d78cbdc5dc6'
down_revision = 'c426972d529a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('customers', sa.Column('auth0_id', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'customers', ['auth0_id'])
    op.add_column('ships', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'ships', 'categories', ['category_id'], ['id'])
    op.drop_constraint('ships_type_id_fkey', 'ships', type_='foreignkey')
    op.drop_column('ships', 'type_id')
    op.drop_table('types')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ships', sa.Column('type_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ships', type_='foreignkey')
    op.create_foreign_key('ships_type_id_fkey', 'ships', 'types', ['type_id'], ['id'])
    op.drop_column('ships', 'category_id')
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column('customers', 'auth0_id')
    op.create_table('types',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='types_pkey'),
    sa.UniqueConstraint('name', name='types_name_key')
    )
    op.drop_table('categories')
    # ### end Alembic commands ###
