"""Add total_sold field to Ship and created_at to OrderItem to support basic admin functionality.

Revision ID: c783ac6f8c44
Revises: 82e82c504529
Create Date: 2020-06-14 11:25:29.534113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c783ac6f8c44'
down_revision = '82e82c504529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('ships', sa.Column('total_sold', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ships', 'total_sold')
    op.drop_column('order_items', 'created_at')
    # ### end Alembic commands ###
