"""add color to order item

Revision ID: f61ec522d535
Revises: 5842dab8d19b
Create Date: 2020-06-13 20:49:48.983992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61ec522d535'
down_revision = '5842dab8d19b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('color', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'color')
    # ### end Alembic commands ###
